sudo: required
services:
  - docker

before_install:
  - docker build -t learndockerkube/docker-react -f Dockerfile.dev .

script:
  - docker run learndockerkube/docker-react npm run test -- --coverage